import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import puppeteer from "puppeteer-extra";
import StealthPlugin from "puppeteer-extra-plugin-stealth";
puppeteer.use(StealthPlugin());
const CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const envText = fs.readFileSync(path.join(path.dirname(fileURLToPath(import.meta.url)), "..", ".env"), "utf8");
const raw = (envText.split("\n").find((l)=>l.startsWith("WEBSHARE_PROXIES="))??"").slice(17).replace(/^["']|["']$/g,"");
const P = raw.split(/[,\n]/).map(s=>s.trim()).filter(Boolean);
const u = new URL(P[0]); const proxy={server:`${u.hostname}:${u.port}`,username:decodeURIComponent(u.username),password:decodeURIComponent(u.password)};
const b = await puppeteer.launch({executablePath:CHROME,headless:true,args:[`--proxy-server=${proxy.server}`,"--no-sandbox"]});
const page = await b.newPage();
await page.authenticate({username:proxy.username,password:proxy.password});
await page.goto("https://www.bing.com/search?q="+encodeURIComponent("Munchkin Manor Early Learning Centre Carlingford NSW childcare"),{waitUntil:"domcontentloaded",timeout:25000});
// Bing shows the true URL in a <cite> inside each .b_algo
const cites = await page.evaluate(()=>Array.from(document.querySelectorAll(".b_algo cite")).map(c=>c.innerText).slice(0,8));
console.log("CITES (display URLs):");
cites.forEach(c=>console.log("  ", c));
await b.close();
